logging:
  file: mst-user-service.log

server:
  port: ${SERVER_PORT:8090}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:mst_user}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:dev}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 50
      max-wait: 10000
      test-on-borrow: true
      initial-size: 5
      min-idle: 5
      validation-query: SELECT 1
  redis:
    host: ${SPRING_REDIS_HOST:127.0.0.1}
    port: 6379
    database: ${SPRING_REDIS_DATABSE:5}
    pool:
      maxActive: 500
      maxIdle: 100
      maxWait: 1000
    ssl: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

security:
  jwt:
    secret: ${JWT_SECRET:_SEMS_JWT_SECRET_201708240805987}
    expiration-in-seconds: 600000

flyway:
  locations: db/migration
  enabled: true